---
- name: Test MySQL replica
  hosts: wordpress_server
  become: true

  vars:
    db_root_password: root_pass

  tasks:
    - name: Create schema in master
      community.mysql.mysql_db:
        name: testdatab
        login_user: root
        login_password: "{{ db_root_password }}"
        login_host: 127.0.0.1
        login_port: 3306
        state: present

    - name: Create table in master
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db_root_password }}"
        login_host: 127.0.0.1
        login_port: 3306
        query: >
          CREATE TABLE IF NOT EXISTS testdatab.test_table (
            id INT AUTO_INCREMENT PRIMARY KEY,
            text VARCHAR(255),
            text2 VARCHAR(255)
          );

    - name: Insert data in master
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db_root_password }}"
        login_host: 127.0.0.1
        login_port: 3306
        query: |
          INSERT INTO testdatab.test_table (text, text2) VALUES
          ('test1', 'test1'),
          ('test2', 'test2'),
          ('test3', 'atutnetest3');

    - name: Wait for replication sync
      pause:
        seconds: 10

    - name: Stop master container
      community.docker.docker_container:
        name: wordpress_db-master
        state: stopped

    - name: Query replica data
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db_root_password }}"
        login_host: 127.0.0.1
        login_port: 3307
        query: SELECT * FROM testdatab.test_table;
      register: replica_data

    - name: Display replica data
      debug:
        var: replica_data.query_result

    - name: Start master container
      community.docker.docker_container:
        name: wordpress_db-master
        state: started
